[project]
name = "birthdaybot"
version = "0.1.0"
description = "A simple birthday bot in Python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "discord-py>=2.5.2",
    "pickledb>=1.3.2",
    "python-dateutil>=2.9.0.post0",
    "python-dotenv>=1.1.1",
    "tzdata>=2025.2",
]
